FROM n8nio/n8n

ENV NODE_ENV=production

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=123456

ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https

ENV EXECUTIONS_PROCESS=main
ENV N8N_RUNNERS_ENABLED=true

EXPOSE 5678
